### ISSUE TITLE
Material-Widgets Thermostat keine Funktion

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis-2-widgets-material#172]
Hallo,

Das Widget hat keine Funktion bzw. ist Fehlerhaft.

![Screenshot (257)](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/41079106/2fdd7a03-d459-4ff4-8147-95662eeb6324)

Version: 1.0.0
VIS2 : 2.2.2
Admin: 6.9.2
Node.js: v18.17.1
NPM: 9.6.7

**Comment by ipod86** [comment]
Das selbe bei mir.

**Comment by ipod86** [comment]
Ist das Problem in der 1.2.1 behoben?

Bei mir macht es immer noch nichts.

![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/a3922fda-f90c-48b0-84ab-2300db974120)

![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/022dec9a-2b50-46f1-842d-44b4e93eef6b)


Das Diagramm sieht auch was komisch aus:
![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/00d1dee2-2b36-4cd4-910f-54ffecde688d)

In eCharts habe ich es im Moment so:
![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/c53cbbb4-297c-4365-9cee-56cb56ca6c5d)

Mit den Entwicklertools kenne ich mich nicht aus.
Das steht da:

`bootstrap.jsx:16 iobroker.vis-2@2.2.7 using theme "colored"
Prompt.js:14 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:15 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:16 Help us to create open source project with reactJS!
Prompt.js:17 See you :)
instrument.ts:144 Skip script "info" ../adapter/info/lib/js/commons.js
instrument.ts:144 Skip script "info" ../adapter/info/lib/js/popupnews.js
instrument.ts:144 Skip script "info" widgets/info/js/info.js
2instrument.ts:144 Skip script "info" inline
instrument.ts:144 Skip script "jqplot" widgets/jqplot/js/jquery.jqplot.min.js
2instrument.ts:144 Skip script "jqplot" inline
3instrument.ts:144 Skip script "swipe" inline
instrument.ts:144 Skip script "tabs" inline
instrument.ts:144 Skip script "trashschedule" widgets/trashschedule/js/trashschedule.js
instrument.ts:144 Skip script "trashschedule" inline
instrument.ts:144 Ignored info/tplInfoMessages because not used in project
instrument.ts:144 Ignored info/tplInfoCalendar because not used in project
instrument.ts:144 Ignored jqplot/tplJqplotGauge because not used in project
instrument.ts:144 Ignored swipe/tplSwipe because not used in project
instrument.ts:144 Ignored swipe/tplCarousel because not used in project
instrument.ts:144 Ignored trashschedule/tplTrashscheduleHelper because not used in project
instrument.ts:144 Common user CSS not found: Not exists
(anonymous) @ instrument.ts:144
48Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was not upgraded to HTTPS because its URL's host is an IP address.
instrument.ts:144 [2023-09-19T05:59:31.659Z] +SUBSCRIBE: 0_userdata.0.example_state
instrument.ts:144 [2023-09-19T05:59:31.660Z] +SUBSCRIBE: echarts.0.Heizung.Ben-Henri_copy
instrument.ts:144 [2023-09-19T05:59:31.661Z] +SUBSCRIBE: 0_userdata.0.VIS.Tabellen.device_watcher
VM208 main.5f66c5d9.js:2 iobroker.echarts-show@1.5.4 using theme "colored"
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_translations_js.395fc3f6.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/openweathermap/static/js/src_translations_js.8cc6492a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
instrument.ts:144 [2023-09-19T05:59:36.190Z] -UNSUBSCRIBE: 0_userdata.0.example_state
instrument.ts:144 [2023-09-19T05:59:36.193Z] -UNSUBSCRIBE: echarts.0.Heizung.Ben-Henri_copy
instrument.ts:144 [2023-09-19T05:59:36.198Z] -UNSUBSCRIBE: 0_userdata.0.VIS.Tabellen.device_watcher
instrument.ts:144 [2023-09-19T05:59:36.213Z] +SUBSCRIBE: 0_userdata.0.example_state
instrument.ts:144 [2023-09-19T05:59:36.221Z] +SUBSCRIBE: echarts.0.Heizung.Ben-Henri_copy
instrument.ts:144 [2023-09-19T05:59:36.228Z] +SUBSCRIBE: 0_userdata.0.VIS.Tabellen.device_watcher
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Generic_jsx-src_ObjectChart_jsx.b796934b.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Thermostat_jsx.9fe80f2d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Actual_jsx-node_modules_babel_runtime_helpers_esm_setPrototypeOf_js.70ad77f0.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Components_DoorAnimation_js-src_Components_LockAnimation_js.05f2a81b.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Blinds_jsx-src_Generic_jsx.aff9b982.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Lock_jsx.40dd2216.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Clock_jsx.a7c0e64d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_RGBLight_jsx-node_modules_babel_runtime_helpers_esm_extends_js-node_modules_babel_runtime-b72c90.74bca79b.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_ViewInWidget_jsx.47d8f677.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Player_jsx.d3deecb7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/openweathermap/static/js/src_react-weather_Weather_js-webpack_sharing_consume_default_iobroker_vis-2-widgets-react-dev-fe17a4.08a2daf7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/openweathermap/static/js/src_Weather_jsx-node_modules_babel_runtime_helpers_esm_objectSpread2_js-node_modules_babel_ru-577953.c93194ca.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Wizard_jsx.a824b7b9.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Components_BlindsBase_js.a97ca885.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_SimpleState_jsx.ecde697f.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Switches_jsx.846eb8e0.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Html_jsx.53c58f1e.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Camera_jsx.32981db1.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_ThemeSwitcher_jsx.43aeca65.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_Security_jsx.1b52604e.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_deviceWidget_js.5b77c3f1.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/js/src_WasherDryer_jsx.765e8e3e.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/css/src_Map_jsx-node_modules_leaflet_dist_leaflet_css-node_modules_babel_runtime_helpers_esm_obje-1f1968.c7bfc0ae.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/openweathermap/static/css/src_react-weather_Weather_js-webpack_sharing_consume_default_iobroker_vis-2-widgets-react-dev-fe17a4.83721eea.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/vis-2/widgets/vis-2-widgets-material/static/css/src_RGBLight_jsx-node_modules_babel_runtime_helpers_esm_extends_js-node_modules_babel_runtime-b72c90.3aa647cd.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.99.33:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.js:19 iobroker.echarts-show@1.5.4 using theme "colored"
instrument.ts:144 Read till Tue Sep 19 2023 07:59:40 GMT+0200 (Mitteleuropäische Sommerzeit)`
